### ISSUE TITLE
Timeouts when using split/plugin architecture and server-timing plugin

### ISSUE THREAD

**Issue by gitblit** [elysiajs/elysia-server-timing#1]
**Background**

When using a split architecture...
- plugin with `derive` & `onBeforeHandle`
- individual route that `uses` this plugin
- app that `uses` the individual route

... combined with the `server-timing` plugin, you may/can experience timeouts in request processing.

**Example**

I have created a minimal reproduction repository to demonstrate the problem.
[gitblit/elysia-server-timing-timeouts-repro](https://github.com/gitblit/elysia-server-timing-timeouts-repro)

1. Clone the repo
2. `bun run dev`
3. `bun test`

Then comment this line and repeat:
https://github.com/gitblit/elysia-server-timing-timeouts-repro/blob/main/src/index.ts#L48

**Comment by SaltyAom** [comment]
Should be fixed in Elysia 1.0.10, reference: https://github.com/elysiajs/elysia/commit/e074fd9f9df6a397ee45a2e9c088e59a99f5c9d7.

**Comment by gitblit** [comment]
That looks much better! Thanks!

**Comment by gitblit** [comment]
Actually, I was faked-out. It may be better ... but if `onBeforeHandle` sets status and returns a result it still waits for 5 second timeout.

**Comment by gitblit** [comment]
@SaltyAom should I report this to the main repo instead of the plugin?

**Comment by gitblit** [comment]
I just tried the latest release and it's better. Almost all endpoints in my PoC now complete successfully but for some reason DELETE endpoints still hang and timeout. 🤔 

server-timing 1.0.2 and Elysia 1.0.20.
